### ISSUE TITLE
Get PinCode User Have Entered As String

### ISSUE THREAD

**Issue by rathodmayur93** [thealeksandr/PFLockScreen-Android#15]
I need to get the pin code user have entered as string since the validation of pin code happens at server side.

Currently it provides the encrypted pin code which I can't validate on server.

Please let me know how to get pinCode as string.

Thanks

**Comment by thealeksandr** [comment]
@rathodmayur93 So you want to have your own encryption and validation? If so I'm working on separate UI and encryption logic. Will try to finish it soon

**Comment by thealeksandr** [comment]
@rathodmayur93 another thing. Is this Do you need to send unencrypted pin code string to the server? In my example Im saving encrypted pincode in shared preferences. You can save it on the server side. and load it to compare. It's only works if pincode is not being shared between different devices. But I believe it shouldn't be. Any way I will merge my separation between UI and encryption and you can implement your own if you want
