### ISSUE TITLE
Themeing not working

### ISSUE THREAD

**Issue by cadaniel** [thealeksandr/PFLockScreen-Android#27]
So I'm trying to customize the background color 

My theme

`<resources>

    
    <style name="AppTheme" parent="Theme.AppCompat.Light">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="colorControlNormal">@color/darkGreyText</item>
        <item name="android:textColorHint">@color/greyText</item>
        <item name="pf_lock_screen">@style/MyLockScreenStyle</item>
    </style>

    <style name="AppTheme.RoundedCornerMaterialButton" parent="Widget.AppCompat.Button.Colored">
        <item name="android:background">@drawable/rounded_shape</item>
        <item name="android:textColor">@android:color/white</item>
    </style>

    <style name="MyLockScreenStyle">
        <item name="android:background">@color/colorPrimary</item>
    </style>

</resources>`

The background is still the orange gradient

**Comment by thealeksandr** [comment]
@cadaniel it's strange. I have exact the same configю You sure you applied theme correctly. Did you try other devices?

**Comment by ContextGrid** [comment]
Yes it's not working, Please take a look into it.

**Comment by thealeksandr** [comment]
@ContextGrid can you please provide more details. How you apply the theme? Did you try other devices? What OS you using? Can't reproduce the case

**Comment by waseem786** [comment]
@thealeksandr  I try to change the colour, but nothing works.
Cloned your project, opened in android studio, go-to style file, under `MyLockScreenStyle` I change the background colour to a different. But No changes I see.
How can I solve this issue?

**Comment by vilmaunjan** [comment]
Doesn't work for me either. I am testing in Pixel Android 10
