### ISSUE TITLE
isPinCodeExist() does not exists in PFFingerprintPinCodeHelper?

### ISSUE THREAD

**Issue by TeTRA99** [thealeksandr/PFLockScreen-Android#29]
Hello!

According to home page, that's used to check if the pin exists:

Check if pin code encryption key exist
boolean isExist = PFFingerprintPinCodeHelper.getInstance().isPinCodeExist();

But it seems that isPinCodeExist() is not a valid method for PFFingerprintPinCodeHelper. (?)

**Comment by thealeksandr** [comment]
Hey @TeTRA99 . I think what you need is if "isPinCodeEncryptionKeyExist()"

**Comment by thealeksandr** [comment]
It's doing the same thing as before. Just more accurate name. So it's checks if encryption key is existing. Encryption key is using to decrypt your key. So it's checking if it's exists. Maybe I need diferent name. It's more accurate. But maybe not very clear when to use it

**Comment by TeTRA99** [comment]
Hi @thealeksandr, we were using `isPinExist = PFFingerprintPinCodeHelper.getInstance().isPinCodeEncryptionKeyExist()` until beta 3, now the the same method requires a new parameter (a callback). 
I saw in the readme that .isPinCodeExist() should be used to check if pin code exists, but that one is not a method of PFFingerprintPinCodeHelper -at least in beta 5-..

We are not using a custom encryption.

Perhaps we should implement the callback?

About the naming... perhaps just `encryptionKeyExists` ?

**Comment by thealeksandr** [comment]
@TeTRA99 yeah just implement a call back. The result will be in callback. 
```
PFSecurityManager.getInstance().getPinCodeHelper().isPinCodeEncryptionKeyExist(
                new PFPinCodeHelperCallback<Boolean>() {
                    @Override
                    public void onResult(PFResult<Boolean> result) {
                        if (result.getResult()) {
                            //TODO: Exist
                        } else {
                            //TODO: Doesn't exist
                        }
                    }
                }
        );
```

**Comment by thealeksandr** [comment]
@TeTRA99 is there app already published? Just curious what app is that

**Comment by TeTRA99** [comment]
Will do the callback thx! ;)

Yes, the app is published in the PlayStore, but only for testing purposes so far (beta), no users, and just in Argentina. Its called Buddy4Life.
