### ISSUE TITLE
How to get unencrypted pin or specify custom encryption method?

### ISSUE THREAD

**Issue by wafel82** [thealeksandr/PFLockScreen-Android#3]
In my case I need to synchronise pin code between different platforms (Android/iOS/Web) with the same user logged in. in other words: I need to specify my own pin encryption method to be able to e.g. create pin on Android and later on use it to unlock iOS.

Is this somehow possible with this library?

**Comment by thealeksandr** [comment]
@wafel82 I sorry It only supports local pin like lock screen. And not support custom encryption. I can probably separate UI from encryption logic so You can add your custom encryption with current UI. It's what you want right?

**Comment by lackern** [comment]
@thealeksandr It will be good if UI can be separated from encryption logic. 

Currently we are unable to prompt user to reenter Pin twice during change of Pin.
