### ISSUE TITLE
IPFPinCodeHelper

### ISSUE THREAD

**Issue by hrupin** [thealeksandr/PFLockScreen-Android#32]
Good time of day.
The library is super, thanks.

I can not figure out how to connect custom encryption?
I inherited the IPFPinCodeHelper class and override methods. But they do not start (((

And another question is how can I get a non-encrypted pincode? or how decrypt?

Thank you for you answer and help

**Comment by thealeksandr** [comment]
Hey @hrupin. You can set your own encryption method as ```PFSecurityManager.getInstance().setPinCodeHelper(new TestPFPinCodeHelperImpl());```

**Comment by thealeksandr** [comment]
@hrupin there is no method to get decrypted pin code. You can only use checkPin method to check if string is correct pincode or not.

**Comment by hrupin** [comment]
Thaks very match

when checking pin code I get an error. Custom encryption is disabled. What could be the problem? Thank you in advance
`
1557789584.717 5357-5357 W/System.err: javax.crypto.IllegalBlockSizeException
1557789584.774 5357-5357 W/System.err:     at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
1557789584.775 5357-5357 W/System.err:     at javax.crypto.Cipher.doFinal(Cipher.java:2055)
1557789584.775 5357-5357 W/System.err:     at com.beautycoder.pflockscreen.security.PFSecurityUtils.decode(PFSecurityUtils.java:135)
1557789584.775 5357-5357 W/System.err:     at com.beautycoder.pflockscreen.security.PFFingerprintPinCodeHelper.checkPin(PFFingerprintPinCodeHelper.java:65)
1557789584.775 5357-5357 W/System.err:     at com.beautycoder.pflockscreen.viewmodels.PFPinCodeViewModel.checkPin(PFPinCodeViewModel.java:31)
1557789584.775 5357-5357 W/System.err:     at com.beautycoder.pflockscreen.fragments.PFLockScreenFragment$6.onCodeCompleted(PFLockScreenFragment.java:311)
1557789584.775 5357-5357 W/System.err:     at com.beautycoder.pflockscreen.views.PFCodeView.input(PFCodeView.java:84)
1557789584.775 5357-5357 W/System.err:     at com.beautycoder.pflockscreen.fragments.PFLockScreenFragment$1.onClick(PFLockScreenFragment.java:187)
1557789584.775 5357-5357 W/System.err:     at android.view.View.performClick(View.java:6597)
1557789584.775 5357-5357 W/System.err:     at android.view.View.performClickInternal(View.java:6574)
1557789584.775 5357-5357 W/System.err:     at android.view.View.access$3100(View.java:778)
1557789584.776 5357-5357 W/System.err:     at android.view.View$PerformClick.run(View.java:25885)
1557789584.776 5357-5357 W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
1557789584.776 5357-5357 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
1557789584.776 5357-5357 W/System.err:     at android.os.Looper.loop(Looper.java:193)
1557789584.777 5357-5357 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
1557789584.777 5357-5357 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
1557789584.777 5357-5357 W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
1557789584.777 5357-5357 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
1557789584.804 5357-5357 W/System.err: Caused by: android.security.KeyStoreException: Unknown error
1557789584.804 5357-5357 W/System.err:     at android.security.KeyStore.getKeyStoreException(KeyStore.java:839)
1557789584.804 5357-5357 W/System.err:     at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
1557789584.804 5357-5357 W/System.err:     at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
1557789584.805 5357-5357 W/System.err: 	... 18 more

`
