### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by pdarcos** [thealeksandr/PFLockScreen-Android#45]
Hi all,

Great project. Very very useful.

My question is whether the project is still being updated or has it been abandoned.
Does it work on Android 10, for example?

I see some PR's from May that have yet to be merged so I'm not sure this project is still active.

Thanks!

**Comment by pdarcos** [comment]
I guess not :(
Too bad. It was an excellent project

**Comment by thealeksandr** [comment]
@pdarcos Still alive. Going to update soon.

**Comment by pdarcos** [comment]
Thanks @thealeksandr 

Looking forward to the updates!
